<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Clientes\Create\CreateClienteCommandValidator.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroservicioClientes.Domain\MicroservicioClientes.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Clientes\Create\CreateClienteCommandValidator.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
